config/routes.rb
BlockBrowser::Application.routes.draw do

  get 'blocks' => 'blocks#index', as: :blocks
  get 'block/:id' => 'blocks#show', as: :block
  get 'tx/:id' => 'tx#show', as: :tx
  get 'script/:id' => 'scripts#show', as: :script
  get 'script/:script_sig/:pk_script' => 'scripts#show'
  get 'script/:script_sig/:pk_script/:sig_hash' => 'scripts#show'
  get 'script' => 'scripts#show'
  get 'address/:id/unspent' => 'address#unspent', as: :address_unspent
  get 'address/:id' => 'address#show', as: :address

  get 'search/:search' => 'search#search'
  get 'search' => 'search#search', as: :search

  get 'unconfirmed' => 'blocks#unconfirmed', as: :unconfirmed
  get 'scripts/:type' => 'scripts#index', as: :scripts
  get 'p2sh_scripts/:type' => 'scripts#p2sh_index', as: :p2sh_scripts

  get 'relay_tx' => 'relay#relay_tx'
  post 'relay_tx' => 'relay#relay_tx'

  get 'api' => 'api#index', as: :api
  get 'api/block' => 'api#block', as: :block_api
  get 'api/tx' => 'api#tx', as: :tx_api
  get 'api/address' => 'api#address', as: :address_api
  get 'api/relay' => 'api#relay', as: :relay_api
  get 'api/stats' => 'api#stats', as: :stats_api
  get 'api/schema' => 'api#schema', as: :schema_api

  get 'graphs' => 'blocks#graphs', as: :graphs

  get 'about' => 'blocks#about', as: :about
  get 'stats' => 'stats#stats', as: :stats
  get 'source' => 'source#source', as: :source

  if Bitcoin.network_project == :namecoin
    get 'names' => 'names#index', as: :names
    get 'name/heights/*name' => 'names#heights', as: :name_heights
    get 'name/*name' => 'names#show', as: :name
    get 'api/name' => 'api#name', as: :name_api
  end

  root :to => 'blocks#index'

end

app/controllers/blocks_controller.rb
require 'timeout'
require 'method_source'

class BlocksController < ApplicationController

  def index
    @per_page = 20
    STORE.instance_eval { @head = nil }
    height = STORE.height
    height = params[:height].to_i  if params[:height] && params[:height].to_i < height
    height = (@per_page - 1)  if height < @per_page
    @blocks = STORE.db[:blk].filter("height <= ?", height).where(chain: 0).order(:height).limit(@per_page).reverse
    @page_title = "Recent Blocks"
  end

  def show
    @block = STORE.block(params[:id])
    return render_error("Block #{params[:id]} not found.", 404)  unless @block
    @siblings = STORE.db[:blk].where(prev_hash: @block.prev_block_hash.blob)
                .reject {|b| b[:id] == @block.id }
                .map {|b| STORE.wrap_block(b) }
    @page_title = "Block Details"
    respond_with(@block, with_next_block: true, with_nid: true, with_address: true, with_next_in: true)
  end

end

app/views/blocks/_blk.html.haml
%td
  %a{:href => block_path(blk[:hash].hth)}= blk[:height]
%td
  %a{:href => block_path(blk[:hash].hth)}= blk[:hash].hth
%td= format_time blk[:time], :short
%td.right= number_with_delimiter STORE.db[:blk_tx].where(blk_id: blk[:id]).count
%td.right= number_to_human_size blk[:blk_size]
%td.right= format_amount STORE.db[:blk_tx].where(blk_id: blk[:id]).join(:tx, id: :tx_id).join(:txout, tx_id: :id).map{|o|o[:value]}.inject(:+)

app/views/blocks/_tx.html.haml
%tr{:class => cycle('odd', 'even')}
  %td= link_to(truncate(tx.hash, :length => 16), tx_path(tx.hash))
  %td
    %table.tx_ins{cellpadding: 0, cellspacing: 0}
      - if tx.in.size == 1 && tx.in[0].coinbase?
        %tr
          %td coinbase
      - else
        - tx.in.map do |i|
          - prev_tx = STORE.db[:tx][hash: i.prev_out_hash.reverse.to_sequel_blob]
          - prev_out = STORE.db[:txout][tx_id: prev_tx[:id], tx_idx: i.prev_out_index]
          - if prev_out
            %tr
              - addr = Bitcoin::Script.new(prev_out[:pk_script]).get_address
              %td= address_link(addr)
              %td (#{format_amount prev_out[:value]})
          - else
            %tr
              %td not seen

  %td
    %table.tx_outs{cellpadding: 0, cellspacing: 0}
      - tx.out.map do |o|
        %tr
          %td
            - if o.parsed_script.type == :unknown
              %span{class: "error"} Unknown script type
            - elsif o.parsed_script.type == :op_return
              OP_RETURN (provably burned)
            - else
              - o.get_addresses.map do |addr|
                = address_link(addr)
                %br/
          %td (#{format_amount o.value})
  %td.right= number_to_human_size tx.to_payload.bytesize
  %td.value= format_amount(tx.out.map(&:value).sum)

app/views/blocks/about.html.haml
- @page_title = "About"

%h3 About

%p
  This is a #{link_to "bitcoin", "http://bitcoin.org"} blockchain browser written in ruby
  using the #{link_to "bitcoin-ruby", "http://github.com/lian/bitcoin-ruby"} library.

%p
  It allows you to view the technical details that make up the blockchain, and also
  query them easily via the #{link_to "API", api_path}.

%h3 License

%p
  The code is open source and available at
  = link_to "block_browser", "http://github.com/mhanne/block_browser"
  under the terms of the GNU AGPL license.

%p
  This instance is currently running git commit #{`git rev-parse HEAD`.strip}.
  %br/
  The current code is also available for direct download here: #{link_to "/source", source_path}.

%h3 Support

%p
  Donations motivate me to invest even more time that I don't have into this project ;)
  = link_to BB_CONFIG['donate'], address_path(BB_CONFIG['donate'])

%p
  Also don't hesitate to send me any comments, bug reports, feature requests or other feedback you might have to the info@ address on this domain (webbtc.com).

app/views/blocks/display_tx.html.haml
%table.details
  %tr
    %th Transaction
    %th= @tx.hash
  %tr
    %th Normalized Hash
    %td= @tx.nhash

  - cache("tx/#{@tx.hash}/details") do
    - if Bitcoin.namecoin?
      %tr
        %th Version
        %td= @tx.ver == 0x7100 ? "Namecoin" : "Bitcoin"
    %tr
      %th Size
      %td= @tx.to_payload.bytesize
    %tr
      %th Inputs
      %td= @tx.in.size
    %tr
      %th Outputs
      %td= @tx.out.size
    - if @tx.in.size == 1 && @tx.in[0].coinbase?
      - input_value = Bitcoin.block_creation_reward(@blk[:height])
    - else
      - input_value = @tx.in.map {|i| STORE.get_tx(i.prev_out.reverse.hth).out[i.prev_out_index].value }.sum rescue '?'
    %tr
      %th Input Value
      %td= format_amount(input_value) rescue '?'
    - output_value = @tx.out.map(&:value).sum
    %tr
      %th Output Value
      %td= format_amount(output_value)
    %tr
      %th Fee
      %td= format_amount(input_value - output_value) rescue '?'
    - if @tx.lock_time != 0
      %tr
        %th Lock Time
        %td
          - if @tx.lock_time < 500_000_000
            - block = STORE.db[:blk][height: @tx.lock_time, chain: 0][:hash].hth
            Block #{link_to @tx.lock_time, "/block/#{block}"}
          - else
            #{@tx.lock_time} (#{format_time Time.at(@tx.lock_time)})
    %tr
      %th Formats
      %td
        = link_to "[json]", "/tx/#{@tx.hash}.json"
        = link_to "[hex]", "/tx/#{@tx.hash}.hex"
        = link_to "[binary]", "/tx/#{@tx.hash}.bin"

%h3 Inputs
%table.list
  %tr
    %th IDX
    %th Type
    %th Previous Output
    %th Value
    %th From Address
    %th Script
    - if display_sequence = @tx.in.map(&:sequence).any? {|s| s.unpack("I")[0] != 0xffffffff }
      %th Sequence
    %th Debug


  - @tx.in.each_with_index do |txin, idx|
    %tr{:class => cycle('odd', 'even')}
      - prev_tx = STORE.get_tx(txin.prev_out.reverse.hth)
      - prev_out = prev_tx.out[txin.prev_out_index] if prev_tx

      - cache("tx/#{@tx.hash}/in/#{idx}/#{!!prev_out}") do
        %td= idx
        - if txin.coinbase?
          %td generation
          %td none
          %td.value= format_amount(Bitcoin.block_creation_reward(@blk[:height]))
          %td -
          %td= txin.script_sig.unpack("H*")[0]
        - else
          - if prev_out
            %td
              = link_to(prev_out.type, "/scripts/#{prev_out.type}")
              - if prev_out.type == :script_hash
                %br/
                (#{link_to txin.p2sh_type, "/p2sh_scripts/#{txin.p2sh_type}"})
            %td
              = link_to(truncate(prev_out.get_tx.hash, :length => 16), tx_path(prev_out.get_tx.hash))
              = "/ #{txin.prev_out_index}"
            %td.value= format_amount(prev_out.value) rescue "?"
            - if prev_out.get_address
              %td
                - prev_out.get_addresses.each do |address|
                  = address_link(address)
                  %br
            - else
              %td not seen
            %td
              %pre
                = Bitcoin::Script.new(txin.script_sig).to_string.split(" ").join("\n")
            - if display_sequence
              %td= txin.sequence.unpack("I")[0].to_s(16)
            %td= link_to "Run Script", script_path("#{@tx.hash}:#{idx}")
          - else
            %td{:colspan => 5} not seen

%h3 Outputs
%table.list
  %tr
    %th IDX
    %th Type
    %th Next Input
    %th Value
    %th To Address
    %th Script
    %th Debug
  - @tx.out.each_with_index do |txout, idx|
    - next_input = STORE.db[:txin][prev_out: @tx.hash.htb.reverse.to_sequel_blob, prev_out_index: idx]
    %tr{:class => cycle('odd', 'even')}
      - cache("tx/#{@tx.hash}/out/#{idx}/#{!!next_input}") do
        - next_input = STORE.wrap_txin(next_input)
        - script = Bitcoin::Script.new(txout.pk_script) rescue nil
        %td= idx
        %td
          - type = txout.parsed_script.type
          = link_to(type, "/scripts/#{type}")
          - if type == :script_hash
            %br/
            - if next_in = txout.get_next_in
              (#{link_to next_in.p2sh_type, "/p2sh_scripts/#{next_input.p2sh_type}"})
            - else
              (unspent)
        %td
          - if next_input
            - tx_hash = next_input.get_tx.hash
            = link_to(truncate(tx_hash, :length => 16, :omission => '...'), tx_path(tx_hash))
            = "/ #{next_input.tx_idx}"
          - else
            not seen

        %td.value= format_amount(txout.value)
        %td
          - case type
          - when :pubkey, :pubkey_hash, :script_hash
            = address_link(txout.parsed_script.get_address)
          - when :multisig
            - addrs = script.get_multisig_addresses
            multisig (#{script.get_signatures_required} of #{script.get_keys_provided}):
            %br/
            - addrs.each do |address|
              = address_link(address)
              %br
          - when :op_return
            - if script.get_op_return_data
              Data: #{script.get_op_return_data}
            - else
              (No data)
          - if Bitcoin.namecoin? && script.is_namecoin?
            - name = txout.get_namecoin_name
            - if name.name
              #{link_to(name.name, name_path(name.name))}: #{name.value || name.hash}
            - else
              Hash: #{name.hash}
            %br
            = address_link(txout.get_address)
          - if script.type == :unknown
            %span{class: "error"} Unknown script type
        %td
          %pre= script.to_string rescue "?"
        %td
          - if next_input
            = link_to "Run Script", script_path("#{next_input.get_tx.hash}:#{next_input.tx_idx}")

app/views/blocks/error.html.haml
- @page_title = "Error"
%h3.error= @error

app/views/blocks/error.json.erb
{"error": "<%= @error %>"}

app/views/blocks/index.html.haml
%table#blocks.list
  %tr
    %th Height
    %th Hash
    %th Time
    %th Tx
    %th Size
    %th Total
  %tbody.blocks
    - @blocks.each do |block|
      %tr{:class => cycle('odd','even')}
        - cache("block/#{block[:hash].hth}/list_item") do
          = render :partial => "blk", :object => block

- if STORE.db.class.name =~ /Sequel/
  - if @blocks.first[:height] < STORE.height
    = link_to "<<", "?height=#{@blocks.first[:height] + @per_page}", :style => "float: left"
  - if @blocks.all.last[:height] > 0
    = link_to ">>", "?height=#{@blocks.all.last[:height] - 1}", :style => "float: right"
- else
  - if @blocks.first.height < STORE.height
    = link_to "<<", "?height=#{@blocks.first.height + @per_page}", :style => "float: left"
  - if @blocks.last.height > 0
    = link_to ">>", "?height=#{@blocks.last.height - 1}", :style => "float: right"

app/views/blocks/show.html.haml
%table.details
  - cache("block/#{@block.hash}/details_1") do
    %tr
      %th Block
      %th= @block.hash
    %tr
      %th Height
      %td
        = @block.height
        - unless @block.chain == 0
          %span{style: "color: red"} (Side Chain)
    - if @siblings.any?
      %tr
        %th Siblings
        %td= @siblings.map {|s| link_to s.hash, block_path(s.hash) }.join("<br/>").html_safe
    %tr
      %th Prev Block
      %td= link_to @block.prev_block_hash.reverse_hth, block_path(@block.prev_block_hash.reverse_hth)
  %tr
    %th Next Block
    - blk = STORE.db[:blk][prev_hash: @block.hash.htb.to_sequel_blob, chain: @block.chain]
    - if blk
      %td= link_to(blk[:hash].hth, block_path(blk[:hash].hth))
    - else
      %td not seen
  - cache("block/#{@block.hash}/details_2") do
    %tr
      %th Merkle Root
      %td= @block.mrkl_root.reverse.unpack("H*")[0]
    %tr
      %th Time
      %td= format_time @block.time
    %tr
      %th Transactions
      %td= number_with_delimiter @block.tx.size
    %tr
      %th Size
      %td= number_to_human_size @block.to_payload.bytesize
    %tr
      %th Total Value
      %td= format_amount(@block.tx.map(&:out).flatten.map(&:value).sum)
    %tr
      %th Block Work
      %td= number_with_delimiter @block.block_work
    %tr
      %th Chain Work
      %td= number_with_delimiter @block.work
    %tr
      %th Formats
      %td
        = link_to "[json]", "/block/#{@block.hash}.json"
        = link_to "[hex]", "/block/#{@block.hash}.hex"
        = link_to "[binary]", "/block/#{@block.hash}.bin"

- cache("block/#{@block.hash}/tx") do
  %h3 Transactions
  %table.list
    %tr
      %th Hash
      %th Inputs
      %th Outputs
      %th Size
      %th Value
    = render :partial => 'tx', :collection => @block.tx

app/views/blocks/unconfirmed.html.haml
%table.list
  %tr
    %th Hash
    %th Inputs
    %th Outputs
    %th Size
    %th Value

  = render :partial => 'tx', :collection => @tx