config/routes.rb
BlockBrowser::Application.routes.draw do

  get 'blocks' => 'blocks#index', as: :blocks
  get 'block/:id' => 'blocks#show', as: :block
  get 'tx/:id' => 'tx#show', as: :tx
  get 'script/:id' => 'scripts#show', as: :script
  get 'script/:script_sig/:pk_script' => 'scripts#show'
  get 'script/:script_sig/:pk_script/:sig_hash' => 'scripts#show'
  get 'script' => 'scripts#show'
  get 'address/:id/unspent' => 'address#unspent', as: :address_unspent
  get 'address/:id' => 'address#show', as: :address

  get 'search/:search' => 'search#search'
  get 'search' => 'search#search', as: :search

  get 'unconfirmed' => 'blocks#unconfirmed', as: :unconfirmed
  get 'scripts/:type' => 'scripts#index', as: :scripts
  get 'p2sh_scripts/:type' => 'scripts#p2sh_index', as: :p2sh_scripts

  get 'relay_tx' => 'relay#relay_tx'
  post 'relay_tx' => 'relay#relay_tx'

  get 'api' => 'api#index', as: :api
  get 'api/block' => 'api#block', as: :block_api
  get 'api/tx' => 'api#tx', as: :tx_api
  get 'api/address' => 'api#address', as: :address_api
  get 'api/relay' => 'api#relay', as: :relay_api
  get 'api/stats' => 'api#stats', as: :stats_api
  get 'api/schema' => 'api#schema', as: :schema_api

  get 'graphs' => 'blocks#graphs', as: :graphs

  get 'about' => 'blocks#about', as: :about
  get 'stats' => 'stats#stats', as: :stats
  get 'source' => 'source#source', as: :source

  if Bitcoin.network_project == :namecoin
    get 'names' => 'names#index', as: :names
    get 'name/heights/*name' => 'names#heights', as: :name_heights
    get 'name/*name' => 'names#show', as: :name
    get 'api/name' => 'api#name', as: :name_api
  end

  root :to => 'blocks#index'

end

app/views/layouts/application.html.haml
!!!

%html
  %head
    %title #{BB_CONFIG['network'].capitalize} BlockBrowser - #{@page_title}
    = stylesheet_link_tag    "application"
    = javascript_include_tag "application"
    = csrf_meta_tags
    :javascript
      $(document).ready(function() {
        connect_websocket("#{WS_CONFIG['secure'] ? 'wss' : 'ws'}://#{WS_CONFIG['host']}:#{WS_CONFIG['port']}/");
      })

  %body
    #header
      %h1= link_to BB_CONFIG['network'].capitalize, root_path
      %h2= "- #{@page_title}"
      #search
        = form_tag(search_path, method: "GET") do
          = text_field_tag :search
          = submit_tag "Search"

    = yield

    #footer
      Networks:
      - BB_CONFIG['networks'].each do |name, url|
        - if Bitcoin.network_name == name.to_sym
          %b= name
        - else
          = link_to name, url
      |
      Blocks:
      %span#head_block= link_to STORE.height, block_path(STORE.head_hash)
      |
      Clients:
      %span#client_count ?
      |
      - if Bitcoin.namecoin?
        = link_to "Recent Names", names_path
        |
      = link_to "API", api_path
      |
      = link_to "Relay", relay_tx_path
      |
      = link_to "About", about_path
      |
      = link_to "Stats", stats_path
      |
      = link_to "Dumps", "http://dumps.webbtc.com/#{BB_CONFIG['network']}"
      |
      = link_to BB_CONFIG['donate'], address_path(BB_CONFIG['donate'])